package org.example.movie;

public class MovieGenerator {

  private static final Object[][] MOVIE_DATA = {
      // {title, Category, description, year}

      // ACTION
      { "Die Hard", Category.ACTION, "Off-duty cop thwarts a terrorist takeover of a Los Angeles skyscraper.", "1988" },
      { "Mad Max: Fury Road", Category.ACTION,
          "In a post-apocalyptic wasteland, a rebel warrior and a fugitive team up against a tyrant.", "2015" },
      { "John Wick", Category.ACTION,
          "A retired hitman seeks vengeance after criminals kill his dog and steal his car.", "2014" },
      { "Gladiator", Category.ACTION,
          "A Roman general enslaved becomes a gladiator and plots revenge against a corrupt emperor.", "2000" },
      { "The Dark Knight", Category.ACTION,
          "Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy.", "2008" },
      { "Heat", Category.ACTION,
          "A seasoned detective and a professional thief circle each other in a tense Los Angeles cat-and-mouse.",
          "1995" },
      { "Terminator 2: Judgment Day", Category.ACTION,
          "A reprogrammed Terminator protects a teenager from an advanced liquid-metal assassin.", "1991" },
      { "Raiders of the Lost Ark", Category.ACTION,
          "Archaeologist Indiana Jones races to find the Ark of the Covenant before the Nazis.", "1981" },
      { "Mission: Impossible – Fallout", Category.ACTION,
          "Ethan Hunt races against time to prevent a global catastrophe after a mission goes sideways.", "2018" },
      { "Speed", Category.ACTION, "A bomb is rigged to explode if a city bus drops below 50 mph.", "1994" },
      { "The Bourne Identity", Category.ACTION,
          "An amnesiac assassin pieces together his identity while evading a global manhunt.", "2002" },
      { "Predator", Category.ACTION,
          "An elite military team hunts a deadly alien predator in a Central American jungle.", "1987" },
      { "Top Gun: Maverick", Category.ACTION,
          "A legendary test pilot trains a new generation of Top Gun graduates for a near-impossible mission.",
          "2022" },
      { "Edge of Tomorrow", Category.ACTION,
          "A soldier relives the same deadly battle against alien invaders over and over.", "2014" },
      { "Batman Begins", Category.ACTION,
          "Bruce Wayne trains to become the vigilante protector Gotham City desperately needs.", "2005" },
      { "The Matrix", Category.ACTION,
          "A computer hacker discovers reality is a simulation and joins a rebellion against machines.", "1999" },
      { "Captain America: The Winter Soldier", Category.ACTION,
          "Steve Rogers uncovers a conspiracy threatening S.H.I.E.L.D. while battling a ghost from his past.", "2014" },
      { "Aliens", Category.ACTION,
          "Marines accompany a survivor back to a colony overrun by the alien creatures she barely escaped.", "1986" },
      { "Kill Bill: Volume 1", Category.ACTION,
          "A former assassin awakens from a coma and embarks on a blood-soaked quest for revenge.", "2003" },
      { "Atomic Blonde", Category.ACTION, "An MI6 operative navigates a treacherous web of spies in Cold War Berlin.",
          "2017" },
      { "Sicario", Category.ACTION,
          "An idealistic FBI agent is enlisted by a government task force to combat cartel violence.", "2015" },
      { "Black Hawk Down", Category.ACTION,
          "A small U.S. Army Ranger force is stranded in Mogadishu after a mission goes catastrophically wrong.",
          "2001" },
      { "The Raid: Redemption", Category.ACTION,
          "A SWAT team becomes trapped in a building controlled by a ruthless drug lord.", "2011" },
      { "Point Break", Category.ACTION,
          "An FBI agent goes undercover among surfers suspected of a string of bank robberies.", "1991" },
      { "Olympus Has Fallen", Category.ACTION,
          "A disgraced Secret Service agent must single-handedly retake the White House from terrorists.", "2013" },
      { "Extraction", Category.ACTION,
          "A black-market mercenary is hired to rescue the kidnapped son of an imprisoned crime lord.", "2020" },
      { "The Equalizer", Category.ACTION,
          "A retired black-ops agent comes out of hiding to protect a young woman from Russian mobsters.", "2014" },
      { "Commando", Category.ACTION,
          "A retired Special Forces colonel must rescue his daughter from a deposed dictator.", "1985" },
      { "Uncharted", Category.ACTION,
          "Treasure hunter Nathan Drake embarks on his first adventure alongside wisecracking thief Sully.", "2022" },
      { "Fast & Furious 7", Category.ACTION,
          "The crew faces their most lethal adversary yet while grieving the loss of a fallen brother.", "2015" },
      { "True Lies", Category.ACTION,
          "A secret agent hides his dangerous career from his wife until a terrorist plot brings it all together.",
          "1994" },
      { "Con Air", Category.ACTION,
          "A paroled convict is trapped on a prison transport plane hijacked by the most dangerous criminals in the U.S.",
          "1997" },
      { "Wanted", Category.ACTION,
          "A young accountant discovers his father was an assassin and joins the shadowy guild that trained him.",
          "2008" },
      { "Kingsman: The Secret Service", Category.ACTION,
          "A street kid is recruited by a veteran spy into an elite secret intelligence organisation.", "2014" },
      { "The A-Team", Category.ACTION,
          "A group of Iraq War veterans go rogue to prove their innocence in a government conspiracy.", "2010" },
      { "Salt", Category.ACTION,
          "A CIA operative goes on the run after being accused of being a Russian sleeper agent.", "2010" },
      { "Jack Reacher", Category.ACTION,
          "A former military investigator tracks down the truth behind an apparently open-and-shut murder case.",
          "2012" },
      { "Shooter", Category.ACTION,
          "A retired Marine sniper is framed for an assassination attempt and must clear his name.", "2007" },
      { "Den of Thieves", Category.ACTION,
          "An elite unit of the L.A. Sheriff's Department faces off against a crew planning to rob the Federal Reserve.",
          "2018" },
      { "Hardcore Henry", Category.ACTION,
          "A man wakes up with no memory and must fight through an entire city in first-person view to save his wife.",
          "2015" },
      { "Crank", Category.ACTION,
          "A hitman is poisoned and must keep his adrenaline pumping or the toxin will kill him.", "2006" },
      { "Man on Fire", Category.ACTION,
          "A disillusioned mercenary becomes a ruthless avenger after the young girl he protected is kidnapped.",
          "2004" },
      { "Equalizer 2", Category.ACTION,
          "Robert McCall delivers justice to those who prey on the innocent, now facing his past.", "2018" },
      { "Nobody", Category.ACTION,
          "A suburban family man's secret past as a deadly government agent is violently reawakened.", "2021" },
      { "The Gray Man", Category.ACTION,
          "A globe-trotting CIA operative becomes the target of his own agency and a ruthless mercenary.", "2022" },
      { "Bullet Train", Category.ACTION,
          "Five assassins aboard a fast-moving train discover their missions are all interrelated.", "2022" },
      { "Ambulance", Category.ACTION,
          "Two thieves hijack an ambulance after a bank robbery goes wrong, with a paramedic and patient on board.",
          "2022" },
      { "The Night Eats the World", Category.ACTION,
          "A man wakes up in Paris to find himself the sole survivor in a city overrun by zombies.", "2018" },
      { "RoboCop", Category.ACTION,
          "In a crime-ridden future Detroit, a slain cop is revived as a cybernetic law-enforcer.", "1987" },
      { "Dredd", Category.ACTION,
          "In a violent future city, a veteran judge and a rookie trainee are trapped in a high-rise controlled by a drug lord.",
          "2012" },

      // COMEDY
      { "The Hangover", Category.COMEDY,
          "Three friends must piece together the night before after waking up to find their friend missing before his wedding.",
          "2009" },
      { "Superbad", Category.COMEDY,
          "Two co-dependent high school seniors have one last adventure before parting ways for college.", "2007" },
      { "Step Brothers", Category.COMEDY,
          "Two middle-aged man-children become step brothers and are forced to share a room.", "2008" },
      { "Anchorman: The Legend of Ron Burgundy", Category.COMEDY,
          "An arrogant San Diego news anchor's world is upended by a talented female reporter.", "2004" },
      { "Dumb and Dumber", Category.COMEDY,
          "Two dim-witted friends drive across the country to return a briefcase to its beautiful owner.", "1994" },
      { "Bridesmaids", Category.COMEDY,
          "Competition between the maid of honor and a wealthy bridesmaid to be the bride's best friend turns ugly.",
          "2011" },
      { "21 Jump Street", Category.COMEDY,
          "Two underperforming cops are assigned to an undercover unit posing as high school students.", "2012" },
      { "Game Night", Category.COMEDY,
          "A couple's game night turns into a real-life mystery when one participant is abducted by actual criminals.",
          "2018" },
      { "Office Space", Category.COMEDY,
          "A software engineer decides to rebel against his soul-crushing corporate job after hypnotherapy goes awry.",
          "1999" },
      { "Tropic Thunder", Category.COMEDY,
          "On the set of a Vietnam War film, actors are dropped into a real jungle conflict.", "2008" },
      { "Borat", Category.COMEDY,
          "A Kazakh journalist travels to America to make a documentary and discovers the country's quirks.", "2006" },
      { "What We Do in the Shadows", Category.COMEDY,
          "A documentary crew follows a group of vampire flatmates navigating modern life in New Zealand.", "2014" },
      { "Knives Out", Category.COMEDY,
          "A detective investigates the death of a wealthy crime novelist at the family estate.", "2019" },
      { "The Grand Budapest Hotel", Category.COMEDY,
          "A legendary concierge and his protégé become embroiled in a theft and a murder mystery.", "2014" },
      { "Crazy, Stupid, Love", Category.COMEDY,
          "A middle-aged man's perfect life unravels when his wife asks for a divorce.", "2011" },
      { "Silver Linings Playbook", Category.COMEDY,
          "A man with bipolar disorder moves back in with his parents and meets a woman with her own history.",
          "2012" },
      { "Groundhog Day", Category.COMEDY,
          "A weatherman finds himself inexplicably living the same day over and over again.", "1993" },
      { "Ferris Bueller's Day Off", Category.COMEDY,
          "A high school student and his two friends take a day off and explore Chicago.", "1986" },
      { "The Big Lebowski", Category.COMEDY,
          "A case of mistaken identity entangles a slacker in a ransom scheme for a millionaire's wife.", "1998" },
      { "Burn After Reading", Category.COMEDY,
          "Idiotic gym employees stumble upon a disc they believe contains CIA intelligence.", "2008" },
      { "Four Weddings and a Funeral", Category.COMEDY,
          "Over the course of five social occasions, a serial bachelor falls for an American woman.", "1994" },
      { "Airplane!", Category.COMEDY,
          "A neurotic ex-fighter pilot must land a passenger plane after the crew falls ill.", "1980" },
      { "The Naked Gun", Category.COMEDY,
          "Bumbling police detective Frank Drebin uncovers a plot to assassinate Queen Elizabeth II.", "1988" },
      { "Monty Python and the Holy Grail", Category.COMEDY,
          "King Arthur and his knights embark on a surreal and absurd quest for the Holy Grail.", "1975" },
      { "Tucker and Dale vs Evil", Category.COMEDY,
          "Two hillbilly best friends are mistaken for murderers by a group of college students on a camping trip.",
          "2010" },
      { "Scott Pilgrim vs. the World", Category.COMEDY,
          "A young musician must defeat his new girlfriend's seven evil exes in order to date her.", "2010" },
      { "Palm Springs", Category.COMEDY, "Two people are stuck in a time loop at a wedding in Palm Springs.", "2020" },
      { "Eurovision Song Contest: The Story of Fire Saga", Category.COMEDY,
          "Two Icelandic musicians get a chance to represent their country in the Eurovision Song Contest.", "2020" },
      { "The Death of Stalin", Category.COMEDY,
          "The Soviet dictator's sudden death sparks a vicious power struggle among his inner circle.", "2017" },
      { "Free Guy", Category.COMEDY,
          "A bank teller discovers he is actually a background character in a video game and decides to become the hero.",
          "2021" },
      { "Spy", Category.COMEDY,
          "A desk-bound CIA analyst volunteers to go undercover to infiltrate the world of a deadly arms dealer.",
          "2015" },
      { "Game Night", Category.COMEDY,
          "A competitive couple's game night turns into a murder mystery when one player goes missing.", "2018" },
      { "Hot Fuzz", Category.COMEDY,
          "A top London cop is transferred to a seemingly idyllic village where accidents keep happening.", "2007" },
      { "Shaun of the Dead", Category.COMEDY,
          "A slacker and his friends must survive a zombie apocalypse while dealing with everyday life problems.",
          "2004" },
      { "The World's End", Category.COMEDY,
          "A man convinces his childhood friends to recreate an epic pub crawl, unaware an alien invasion is underway.",
          "2013" },
      { "This Is the End", Category.COMEDY,
          "Hollywood celebrities play themselves as the apocalypse unfolds at a party.", "2013" },
      { "Zombieland", Category.COMEDY, "Four survivors navigate a zombie apocalypse with very different personalities.",
          "2009" },
      { "Pineapple Express", Category.COMEDY,
          "A stoner and his dealer are on the run from hitmen after witnessing a murder.", "2008" },
      { "Horrible Bosses", Category.COMEDY,
          "Three friends conspire to murder their awful employers after their working lives become intolerable.",
          "2011" },
      { "I Love You, Man", Category.COMEDY,
          "A newly engaged man looks for a best friend so he'll have a best man for his wedding.", "2009" },
      { "Role Models", Category.COMEDY, "Two salesmen are sentenced to community service mentoring troubled youths.",
          "2008" },
      { "Get Hard", Category.COMEDY,
          "Convicted of a crime he didn't commit, a millionaire hires a car-wash attendant to prep him for prison.",
          "2015" },
      { "Walk Hard: The Dewey Cox Story", Category.COMEDY,
          "A parody of musician biopics following the rise and fall of rock legend Dewey Cox.", "2007" },
      { "Year One", Category.COMEDY,
          "Two prehistoric slackers are expelled from their village and embark on an epic journey.", "2009" },
      { "The Other Guys", Category.COMEDY,
          "Two mismatched cops become unlikely heroes when New York's top detective team is eliminated.", "2010" },
      { "Pain & Gain", Category.COMEDY,
          "A group of bodybuilders in Florida get caught up in an extortion ring and a scheme to get rich.", "2013" },
      { "Popstar: Never Stop Never Stopping", Category.COMEDY,
          "A documentary crew follows a pop star as his solo career begins to collapse.", "2016" },
      { "They Came Together", Category.COMEDY,
          "A parody of romantic comedies told as an elaborate story between two friends.", "2014" },
      { "Masterminds", Category.COMEDY,
          "A bumbling armored-car driver is talked into robbing his own company by a former co-worker.", "2016" },
      { "The Nice Guys", Category.COMEDY,
          "A hapless private eye and a hired enforcer investigate a case involving a missing girl in 1970s Los Angeles.",
          "2016" },
      { "10 Cloverfield Lane", Category.COMEDY,
          "After an accident, a woman wakes up in a shelter with two men claiming the outside world is contaminated.",
          "2016" },

      // DRAMA
      { "The Godfather", Category.DRAMA,
          "The aging patriarch of an organized crime dynasty transfers control to his reluctant youngest son.",
          "1972" },
      { "Forrest Gump", Category.DRAMA,
          "A slow-witted but kind-hearted man from Alabama witnesses and influences major events in 20th-century America.",
          "1994" },
      { "Schindler's List", Category.DRAMA,
          "A German industrialist saves more than a thousand Jewish refugees from the Nazis by employing them.",
          "1993" },
      { "Fight Club", Category.DRAMA,
          "An insomniac office worker forms an underground fight club with a soap salesman.", "1999" },
      { "Good Will Hunting", Category.DRAMA,
          "A gifted janitor at MIT catches the attention of a professor after solving an impossible math problem.",
          "1997" },
      { "Shawshank Redemption", Category.DRAMA,
          "Two imprisoned men bond over the years, finding solace and eventual redemption through acts of decency.",
          "1994" },
      { "12 Years a Slave", Category.DRAMA,
          "In the antebellum United States, Solomon Northup is kidnapped and sold into slavery.", "2013" },
      { "Whiplash", Category.DRAMA,
          "A young drummer enrolls at a cutthroat music conservatory where the teacher will stop at nothing to push his students.",
          "2014" },
      { "Manchester by the Sea", Category.DRAMA,
          "A brooding and isolated man becomes the legal guardian of his nephew after his brother dies.", "2016" },
      { "Moonlight", Category.DRAMA,
          "A young black man grapples with his identity and sexuality while growing up in a rough neighborhood in Miami.",
          "2016" },
      { "Parasite", Category.DRAMA,
          "A poor family schemes to become employed by a wealthy household, with dark consequences.", "2019" },
      { "Portrait of a Lady on Fire", Category.DRAMA,
          "On an isolated island, a painter falls for the woman she is commissioned to paint in secret.", "2019" },
      { "Marriage Story", Category.DRAMA,
          "A stage director and his actress wife struggle through a coast-to-coast divorce.", "2019" },
      { "The Irishman", Category.DRAMA,
          "An aging hitman recalls his time with the mob and his involvement with the disappearance of Jimmy Hoffa.",
          "2019" },
      { "Once Upon a Time in America", Category.DRAMA,
          "The story of Jewish gangsters in New York from their childhood through old age.", "1984" },
      { "There Will Be Blood", Category.DRAMA,
          "A silver miner becomes an oil prospector and battles greed, religion, and family in early 20th-century California.",
          "2007" },
      { "No Country for Old Men", Category.DRAMA,
          "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and takes the money.",
          "2007" },
      { "Brokeback Mountain", Category.DRAMA, "A forbidden romance blossoms between two cowboys over the decades.",
          "2005" },
      { "American Beauty", Category.DRAMA,
          "A suburban father has a midlife crisis and becomes infatuated with his daughter's best friend.", "1999" },
      { "Requiem for a Dream", Category.DRAMA,
          "The drug-induced utopias of four Brooklyn residents are shattered when their addictions run rampant.",
          "2000" },
      { "Precious", Category.DRAMA,
          "An obese and abused teenager in Harlem struggles to better herself and escape a brutal home life.", "2009" },
      { "Room", Category.DRAMA,
          "After years of captivity, a mother and her son escape and must now navigate the outside world.", "2015" },
      { "Lion", Category.DRAMA,
          "A five-year-old gets lost in India and is adopted by an Australian family, and later searches for his birth family.",
          "2016" },
      { "Beautiful Boy", Category.DRAMA,
          "A father and son's loving, yet complex relationship is tested by the son's drug addiction.", "2018" },
      { "The Father", Category.DRAMA,
          "An 80-year-old man refuses help from his daughter as he faces the onset of dementia.", "2020" },
      { "Nomadland", Category.DRAMA,
          "A woman sets out on a journey through the American West after losing everything in the Great Recession.",
          "2020" },
      { "The Power of the Dog", Category.DRAMA,
          "A charismatic rancher dominates those around him until his brother brings home a new wife and stepson.",
          "2021" },
      { "Belfast", Category.DRAMA,
          "A young boy and his family navigate the tumult of the 1960s troubles in Northern Ireland.", "2021" },
      { "Aftersun", Category.DRAMA,
          "An adult reflects on a holiday she took with her father years earlier, seeing it through new eyes.",
          "2022" },
      { "The Banshees of Inisherin", Category.DRAMA,
          "On a remote Irish island, the sudden end of a lifelong friendship sends both men down a dark path.",
          "2022" },
      { "All Quiet on the Western Front", Category.DRAMA,
          "A young German soldier experiences the brutal reality of World War I.", "2022" },
      { "Past Lives", Category.DRAMA, "Childhood sweethearts are separated and reunite years later in New York City.",
          "2023" },
      { "Anatomy of a Fall", Category.DRAMA,
          "A woman is suspected of murdering her husband after he falls from their chalet in the Alps.", "2023" },
      { "Oppenheimer", Category.DRAMA,
          "The story of the American scientist who led the development of the first nuclear weapons.", "2023" },
      { "The Zone of Interest", Category.DRAMA,
          "An Auschwitz commandant and his wife work to build a dream life beside the concentration camp.", "2023" },
      { "Tar", Category.DRAMA, "The rise and fall of a renowned female conductor of a major German orchestra.",
          "2022" },
      { "A Separation", Category.DRAMA,
          "A husband and wife are faced with a difficult decision about the future of their daughter.", "2011" },
      { "Incendies", Category.DRAMA,
          "Twins discover their mother's turbulent past while carrying out her enigmatic last wishes in the Middle East.",
          "2010" },
      { "The Lives of Others", Category.DRAMA,
          "In 1984 East Berlin, a Stasi agent surveils a playwright and his actress girlfriend.", "2006" },
      { "Amour", Category.DRAMA,
          "An elderly Parisian couple faces a health crisis that tests the limits of their devotion.", "2012" },
      { "Capernaum", Category.DRAMA, "A Lebanese boy sues his parents for the crime of giving him life.", "2018" },
      { "I, Daniel Blake", Category.DRAMA,
          "A middle-aged carpenter must navigate the bureaucratic welfare system after a heart condition leaves him unable to work.",
          "2016" },
      { "Shoplifters", Category.DRAMA,
          "A family on the outskirts of Tokyo survive by committing petty crimes despite their warm togetherness.",
          "2018" },
      { "Wild Tales", Category.DRAMA,
          "Six short stories exploring the extremes of human behavior when pushed to the brink.", "2014" },
      { "About Elly", Category.DRAMA,
          "A group of Iranian friends on a seaside trip face a crisis when one of them disappears.", "2009" },
      { "Force Majeure", Category.DRAMA,
          "A Swedish family's ski vacation is upended when the father flees an avalanche while leaving his wife and kids behind.",
          "2014" },
      { "The White Ribbon", Category.DRAMA,
          "Strange events precede the outbreak of World War I in a small German village.", "2009" },
      { "Certified Copy", Category.DRAMA,
          "A British author and a French woman spend the day together in Tuscany exploring ideas of authenticity.",
          "2010" },
      { "In the Mood for Love", Category.DRAMA,
          "Two neighbors in 1960s Hong Kong form an intimate bond after discovering their spouses are having an affair.",
          "2000" },
      { "Happy Together", Category.DRAMA,
          "Two gay men travel from Hong Kong to Argentina and their volatile relationship falls apart.", "1997" },
      { "A Brighter Summer Day", Category.DRAMA,
          "In 1960s Taiwan, a young boy drifts into a street gang and falls in love with a leader's girlfriend.",
          "1991" },

      // HORROR
      { "The Shining", Category.HORROR,
          "A family moves into an isolated hotel for the winter and the father is driven to murderous madness by its supernatural forces.",
          "1980" },
      { "It", Category.HORROR,
          "A group of outcast children face their deepest fears when they encounter a shape-shifting monster.",
          "2017" },
      { "Hereditary", Category.HORROR,
          "After the family matriarch dies, a mother discovers dark, disturbing secrets about her ancestry.", "2018" },
      { "A Quiet Place", Category.HORROR,
          "A family struggles to survive in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing.",
          "2018" },
      { "Get Out", Category.HORROR,
          "A young Black man visits his white girlfriend's parents for the weekend, only to uncover unsettling truths.",
          "2017" },
      { "The Conjuring", Category.HORROR,
          "Paranormal investigators help a family terrorized by a dark presence in their farmhouse.", "2013" },
      { "Midsommar", Category.HORROR,
          "A couple travels to Sweden for a midsummer festival, unaware the idyllic retreat hides a sinister pagan cult.",
          "2019" },
      { "It Follows", Category.HORROR,
          "After a sexual encounter, a young woman is pursued by a supernatural entity that only she can see.",
          "2014" },
      { "The Witch", Category.HORROR,
          "In 1630s New England, a Puritan family encounters an increasing amount of evil living on the edge of the woods.",
          "2015" },
      { "Us", Category.HORROR,
          "A family is terrorized by a group of menacing doppelgängers who appear outside their vacation home.",
          "2019" },
      { "Sinister", Category.HORROR,
          "A true-crime writer moves his family into a home where murders were committed, and discovers disturbing footage.",
          "2012" },
      { "Insidious", Category.HORROR,
          "A family looks to prevent evil spirits from trapping their comatose child in another dimension.", "2010" },
      { "The Babadook", Category.HORROR,
          "A single mother is plagued by the reappearance of a monster from her son's storybook.", "2014" },
      { "Annihilation", Category.HORROR,
          "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.",
          "2018" },
      { "Suspiria", Category.HORROR,
          "An American student enrolls in a prestigious German dance academy that is secretly a front for a coven of witches.",
          "2018" },
      { "Black Swan", Category.HORROR,
          "A ballet dancer wins the lead role in Swan Lake only to be consumed by obsession and rivalry.", "2010" },
      { "The Lighthouse", Category.HORROR,
          "Two lighthouse keepers slowly descend into madness on a remote island in the 1890s.", "2019" },
      { "Mandy", Category.HORROR,
          "In 1983, a peaceful couple is attacked by a vicious cult, and the husband becomes a blood-soaked avenger.",
          "2018" },
      { "Color Out of Space", Category.HORROR,
          "A meteorite lands on a family's farm and contaminates the area with a strange alien organism.", "2019" },
      { "The Wailing", Category.HORROR,
          "A police officer investigates a series of mysterious murders that have struck a rural village in Korea.",
          "2016" },
      { "Train to Busan", Category.HORROR,
          "While traveling to Busan by train, a father and daughter must fight for survival as a zombie virus spreads.",
          "2016" },
      { "Raw", Category.HORROR,
          "A strict vegetarian goes to veterinary school and develops a craving for meat, and worse.", "2016" },
      { "Bone Tomahawk", Category.HORROR,
          "A sheriff and his posse ride out to rescue kidnapped townspeople from a tribe of cave-dwelling cannibals.",
          "2015" },
      { "The Girl with All the Gifts", Category.HORROR,
          "A scientist and a teacher living in a dystopian future embark on a journey of survival with a special young girl.",
          "2016" },
      { "The Hunt", Category.HORROR,
          "Twelve strangers wake up in a clearing and realize they are being hunted for sport.", "2020" },
      { "Nope", Category.HORROR, "Ranch owners witness a strange and terrifying discovery on their property.", "2022" },
      { "Barbarian", Category.HORROR, "A woman staying at an Airbnb discovers a dark secret in the basement.", "2022" },
      { "Pearl", Category.HORROR,
          "A woman trapped on her family's farm in 1918 commits shocking acts in pursuit of stardom.", "2022" },
      { "Talk to Me", Category.HORROR,
          "Teenagers discover they can communicate with ghosts using an embalmed hand, with terrifying consequences.",
          "2022" },
      { "M3GAN", Category.HORROR,
          "A roboticist creates an AI doll companion for her orphaned niece, with deadly results.", "2022" },
      { "Smile", Category.HORROR, "A doctor begins experiencing disturbing visions after witnessing a traumatic event.",
          "2022" },
      { "Speak No Evil", Category.HORROR,
          "A Dutch couple vacations with a mysterious couple who turn out to be hiding a dark secret.", "2022" },
      { "The Black Phone", Category.HORROR,
          "A kidnapped boy begins receiving calls from previous victims of the serial killer holding him captive.",
          "2021" },
      { "Titane", Category.HORROR,
          "A serial killer goes on the run after a series of inexplicable events and hides with a grieving fireman.",
          "2021" },
      { "The Card Counter", Category.HORROR,
          "A former military interrogator becomes a poker player in search of redemption.", "2021" },
      { "Lamb", Category.HORROR, "A childless couple in rural Iceland discover a mysterious newborn on their farm.",
          "2021" },
      { "Antlers", Category.HORROR,
          "A schoolteacher and her sheriff brother discover that a student is harboring a dangerous supernatural entity.",
          "2021" },
      { "Last Night in Soho", Category.HORROR,
          "An aspiring fashion designer is transported back to 1960s London in her dreams, where she inhabits a young woman with a dark fate.",
          "2021" },
      { "Saint Maud", Category.HORROR,
          "A pious young nurse becomes obsessed with saving the soul of her hedonistic patient.", "2019" },
      { "Possessor", Category.HORROR,
          "An agent uses brain-implant technology to take control of people's bodies to carry out assassinations.",
          "2020" },
      { "The Platform", Category.HORROR,
          "In a vertical prison, food descends on a platform daily. Those at the top gorge; those at the bottom starve.",
          "2019" },
      { "His House", Category.HORROR,
          "A South Sudanese refugee couple struggles to adapt to their new life in England, haunted by something from home.",
          "2020" },
      { "Run", Category.HORROR,
          "A girl in a wheelchair begins to suspect her mother is keeping a sinister secret from her.", "2020" },
      { "Come Play", Category.HORROR, "A lonely boy befriends a monster that uses his phone to enter the real world.",
          "2020" },
      { "The Empty Man", Category.HORROR,
          "An ex-cop investigates the disappearance of a girl linked to an enigmatic cult.", "2020" },
      { "Freaky", Category.HORROR,
          "A seventeen-year-old girl swaps bodies with a serial killer and has 24 hours to switch back.", "2020" },
      { "Army of Darkness", Category.HORROR,
          "A department store employee is accidentally transported to medieval times and must battle the undead.",
          "1992" },
      { "The Thing", Category.HORROR,
          "An alien organism terrorizes a research station in Antarctica by assuming the form of its victims.",
          "1982" },
      { "Aliens vs Predator", Category.HORROR,
          "Two iconic extraterrestrial species clash, leaving a small team of humans trapped in the middle.", "2004" },
      { "The Mist", Category.HORROR,
          "A freak storm traps townspeople in a supermarket, and an otherworldly mist surrounds them.", "2007" },
      { "30 Days of Night", Category.HORROR,
          "An Alaskan town is left isolated and in total darkness for a month while a horde of vampires attacks.",
          "2007" },

      // SCI_FI
      { "Interstellar", Category.SCI_FI,
          "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
          "2014" },
      { "Blade Runner 2049", Category.SCI_FI,
          "A young blade runner discovers a long-buried secret that could plunge society into chaos.", "2017" },
      { "Arrival", Category.SCI_FI,
          "A linguist is recruited to communicate with alien life forms after twelve spacecraft appear around the world.",
          "2016" },
      { "2001: A Space Odyssey", Category.SCI_FI,
          "After discovering a mysterious artifact, humanity launches an expedition to Jupiter, guided by a sentient computer.",
          "1968" },
      { "Ex Machina", Category.SCI_FI,
          "A young programmer is chosen to evaluate the human qualities of a breakthrough artificial intelligence.",
          "2014" },
      { "Gravity", Category.SCI_FI,
          "Two astronauts work together to survive after an accident leaves them adrift in space.", "2013" },
      { "Moon", Category.SCI_FI,
          "An astronaut stationed alone on the moon makes a shocking discovery as his three-year contract nears its end.",
          "2009" },
      { "District 9", Category.SCI_FI,
          "Aliens are forced to live in slum-like conditions on Earth, and a bureaucrat becomes their unlikely champion.",
          "2009" },
      { "Children of Men", Category.SCI_FI,
          "In a dystopian future where women have become infertile, a former activist must protect the first pregnant woman in 18 years.",
          "2006" },
      { "Annihilation", Category.SCI_FI,
          "A biologist and her team venture into a mysterious zone where nature has gone haywire.", "2018" },
      { "Contact", Category.SCI_FI,
          "A scientist receives a message from deep space that contains instructions for building a mysterious machine.",
          "1997" },
      { "Primer", Category.SCI_FI,
          "Two engineers accidentally discover time travel and struggle with the ethical implications.", "2004" },
      { "Coherence", Category.SCI_FI, "Strange events upend a dinner party on the night a comet passes overhead.",
          "2013" },
      { "The Martian", Category.SCI_FI,
          "An astronaut is presumed dead and left behind on Mars, and must figure out how to survive.", "2015" },
      { "Dune", Category.SCI_FI,
          "A noble family is thrust into a desert world and must navigate complex political and religious forces.",
          "2021" },
      { "Dune: Part Two", Category.SCI_FI,
          "Paul Atreides unites with the Fremen to exact revenge on the conspirators who destroyed his family.",
          "2024" },
      { "The Truman Show", Category.SCI_FI,
          "A man gradually discovers his entire life has been a staged television broadcast.", "1998" },
      { "Eternal Sunshine of the Spotless Mind", Category.SCI_FI,
          "A couple undergoes a procedure to erase their memories of each other after a painful breakup.", "2004" },
      { "Everything Everywhere All at Once", Category.SCI_FI,
          "A middle-aged laundry owner is swept up in an adventure across the multiverse.", "2022" },
      { "Infinity War", Category.SCI_FI,
          "The Avengers combine forces to prevent Thanos from collecting all six Infinity Stones.", "2018" },
      { "Endgame", Category.SCI_FI,
          "After Thanos erases half of life in the universe, the Avengers travel through time to undo his actions.",
          "2019" },
      { "Looper", Category.SCI_FI,
          "A hired killer is tasked with eliminating his future self sent back in time by the mob.", "2012" },
      { "Source Code", Category.SCI_FI,
          "A soldier relives the last eight minutes of a bombing victim's life to identify the bomber.", "2011" },
      { "Upstream Color", Category.SCI_FI,
          "Two strangers are drawn together after a parasitic organism shared between them bonds their identities.",
          "2013" },
      { "Stalker", Category.SCI_FI,
          "A guide leads two clients into a forbidden zone where an allegedly wish-granting room exists.", "1979" },
      { "Solaris", Category.SCI_FI,
          "A psychologist is sent to a station orbiting a remote planet where the crew is experiencing mysterious apparitions.",
          "1972" },
      { "Under the Skin", Category.SCI_FI,
          "An alien entity roams Scotland in a van, seducing lonely men to their demise.", "2013" },
      { "Prospect", Category.SCI_FI,
          "A teenage girl and her father land on a remote moon to mine for gems, but things go wrong.", "2018" },
      { "The Vast of Night", Category.SCI_FI,
          "In 1950s New Mexico, two teenagers investigate a strange audio frequency that may not be of this world.",
          "2019" },
      { "Synchronic", Category.SCI_FI,
          "Two paramedics discover that a designer drug allows users to travel through time.", "2019" },
      { "Beyond the Black Rainbow", Category.SCI_FI,
          "A young woman is held captive in a mysterious institute by a deranged scientist.", "2010" },
      { "Annihilation", Category.SCI_FI,
          "Biologists on an expedition into a mysterious expanding environmental zone face terror and transformation.",
          "2018" },
      { "Tau", Category.SCI_FI,
          "A woman held captive in a smart house tries to befriend the AI that controls it in order to escape.",
          "2018" },
      { "I Am Mother", Category.SCI_FI,
          "A teenage girl is raised by a robot called Mother, designed to repopulate the earth after human extinction.",
          "2019" },
      { "Archive", Category.SCI_FI,
          "A scientist builds increasingly sophisticated androids in an effort to recreate his dead wife.", "2020" },
      { "Oxygen", Category.SCI_FI,
          "A woman wakes in a cryogenic unit with no memory and must piece together who she is before her oxygen runs out.",
          "2021" },
      { "The Midnight Sky", Category.SCI_FI,
          "A scientist in the Arctic races to contact a crew returning from a mission to a habitable moon of Jupiter.",
          "2020" },
      { "Settlers", Category.SCI_FI,
          "A family makes a home on a desolate Mars, but their peace is disturbed by a stranger.", "2021" },
      { "The Adam Project", Category.SCI_FI,
          "A time-traveling fighter pilot teams up with his 12-year-old self on a mission to save the future.",
          "2022" },
      { "Tenet", Category.SCI_FI,
          "A CIA operative is recruited by a secret organization to prevent World War III using time inversion.",
          "2020" },
      { "Reminiscence", Category.SCI_FI,
          "A private investigator navigates a flooded future Miami to recover lost memories for clients.", "2021" },
      { "The Tomorrow War", Category.SCI_FI,
          "A soldier is transported to the future to fight an alien threat, and discovers a shocking secret.", "2021" },
      { "Moonfall", Category.SCI_FI,
          "A former NASA executive discovers the moon is not what we think it is as it threatens to crash into Earth.",
          "2022" },
      { "Vesper", Category.SCI_FI,
          "A teenage girl with biotechnology skills must navigate a brutal world after the collapse of ecosystems.",
          "2022" },
      { "Finch", Category.SCI_FI,
          "An ailing inventor builds a robot to care for his dog after he is gone, in a post-apocalyptic world.",
          "2021" },
      { "Swan Song", Category.SCI_FI,
          "A man diagnosed with a terminal illness secretly creates a clone to take his place for his family.",
          "2021" },
      { "Stowaway", Category.SCI_FI,
          "A three-person crew on a mission to Mars discovers an accidental stowaway whose presence threatens all life aboard.",
          "2021" },
      { "Outside the Wire", Category.SCI_FI,
          "In the future, a drone pilot is sent into a war zone and paired with an android supersoldier.", "2021" },
      { "Oxygen", Category.SCI_FI,
          "A woman trapped in a cryogenic cell must recover her identity and escape before the oxygen runs out.",
          "2021" },
      { "Morgan", Category.SCI_FI,
          "A corporate troubleshooter arrives at a remote research facility to assess a synthetic humanoid who has gone rogue.",
          "2016" },

      // THRILLER
      { "Se7en", Category.THRILLER,
          "Two detectives hunt a serial killer who uses the seven deadly sins as the motives for his crimes.", "1995" },
      { "Gone Girl", Category.THRILLER,
          "On the morning of their fifth anniversary, Nick Dunne's wife Amy mysteriously disappears.", "2014" },
      { "Prisoners", Category.THRILLER,
          "Two girls go missing and the desperate father takes matters into his own hands when police fail.", "2013" },
      { "Zodiac", Category.THRILLER,
          "In the late 1960s, the Zodiac killer terrorizes San Francisco and a cartoonist becomes obsessed with the case.",
          "2007" },
      { "The Silence of the Lambs", Category.THRILLER,
          "An FBI cadet seeks advice from a caged psychopath to help catch another serial killer.", "1991" },
      { "Nightcrawler", Category.THRILLER,
          "A driven man becomes a freelance crime journalist in Los Angeles and his ambition blurs ethical lines.",
          "2014" },
      { "Drive", Category.THRILLER,
          "A stuntman moonlights as a getaway driver and becomes entangled with the mob after falling for a neighbor.",
          "2011" },
      { "Oldboy", Category.THRILLER,
          "A man imprisoned for 15 years without explanation is suddenly released and sets out to find who locked him up.",
          "2003" },
      { "Memento", Category.THRILLER,
          "A man with short-term memory loss uses notes and tattoos to hunt his wife's murderer.", "2000" },
      { "Rear Window", Category.THRILLER,
          "A wheelchair-bound photographer becomes convinced he has witnessed a murder through his apartment window.",
          "1954" },
      { "The Talented Mr. Ripley", Category.THRILLER,
          "A young man is sent to Italy to retrieve a millionaire's son, but he quickly develops an obsession.",
          "1999" },
      { "Parasite", Category.THRILLER,
          "A poor Korean family infiltrates the world of a wealthy family, with dramatic consequences.", "2019" },
      { "Uncut Gems", Category.THRILLER, "A jeweler makes a high-stakes bet that could either save or destroy him.",
          "2019" },
      { "A Simple Favor", Category.THRILLER,
          "A mommy blogger investigates the disappearance of her best friend, a woman with many secrets.", "2018" },
      { "Bird Box", Category.THRILLER,
          "A woman and a pair of children are blindfolded to survive a supernatural entity that kills anyone who sees it.",
          "2018" },
      { "You Were Never Really Here", Category.THRILLER,
          "A traumatized veteran who rescues children from sex traffickers takes on his most difficult assignment yet.",
          "2017" },
      { "Wind River", Category.THRILLER,
          "A native tracker and an FBI agent investigate the murder of a young woman on a Wyoming reservation.",
          "2017" },
      { "The Girl on the Train", Category.THRILLER,
          "A divorcée becomes entangled in a missing persons investigation after witnessing something from her commuter train.",
          "2016" },
      { "10 Cloverfield Lane", Category.THRILLER,
          "After a car accident, a woman wakes up in a bunker with two men who tell her an attack has made the outside uninhabitable.",
          "2016" },
      { "Sicario: Day of the Soldado", Category.THRILLER,
          "A federal agent is hired to instigate a war between rival drug cartels, but the mission goes sideways.",
          "2018" },
      { "Gerald's Game", Category.THRILLER,
          "A woman accidentally kills her husband while handcuffed to a bed in a remote lake house.", "2017" },
      { "Hush", Category.THRILLER,
          "A deaf writer living alone in the woods must survive a masked killer who has found her isolated home.",
          "2016" },
      { "Don't Breathe", Category.THRILLER,
          "Three thieves break into the house of a blind man, not knowing that he has a terrifying secret.", "2016" },
      { "The Gift", Category.THRILLER,
          "A married couple settles in California and is confronted by a man who claims to be an acquaintance of the husband.",
          "2015" },
      { "Searching", Category.THRILLER,
          "A father searches for his missing teenage daughter and finds clues in her online life.", "2018" },
      { "Cam", Category.THRILLER, "A webcam performer becomes obsessed with a doppelgänger who hijacks her account.",
          "2018" },
      { "Upgrade", Category.THRILLER,
          "A man paralyzed in a mugging is implanted with an AI that helps him seek revenge on his attackers.",
          "2018" },
      { "The Autopsy of Jane Doe", Category.THRILLER,
          "A coroner and his son discover disturbing clues about a mysterious unidentified body.", "2016" },
      { "Green Room", Category.THRILLER,
          "A punk rock band witnesses a murder at a neo-Nazi club and must fight to survive.", "2015" },
      { "Blue Ruin", Category.THRILLER, "A vagrant returns home to seek revenge on the family of his parents' killer.",
          "2013" },
      { "A Most Violent Year", Category.THRILLER,
          "In New York City in 1981, the owner of a heating oil company fights to protect his business and family.",
          "2014" },
      { "Coherence", Category.THRILLER,
          "Mysterious events escalate during a dinner party on the night a comet passes close to Earth.", "2013" },
      { "The Place Beyond the Pines", Category.THRILLER,
          "A motorcycle stuntman turns to bank robbery to support his son, which leads to a collision course with a cop.",
          "2012" },
      { "Compliance", Category.THRILLER,
          "A fast-food restaurant manager is manipulated by a caller claiming to be a police officer.", "2012" },
      { "Prisoners Part 2", Category.THRILLER,
          "In a race against time, a detective pursues new leads in a cold case linked to a string of disappearances.",
          "2015" },
      { "The Watcher", Category.THRILLER, "A newly hired babysitter discovers a sinister cult in a small town.",
          "2022" },
      { "Caliber", Category.THRILLER,
          "Two friends on a deer-hunting trip to Scotland make a tragic mistake that spirals out of control.", "2018" },
      { "Reversible", Category.THRILLER,
          "A scientist discovers a drug that can alter memories, but misuse begins to erode reality.", "2019" },
      { "Nocturnal Animals", Category.THRILLER,
          "A wealthy art gallery owner is deeply disturbed by a violent novel her ex-husband wrote, which she suspects is a veiled threat.",
          "2016" },
      { "The Invisible Guest", Category.THRILLER,
          "A successful businessman is accused of a murder he claims he didn't commit and hires a legal strategist.",
          "2016" },
      { "Fractured", Category.THRILLER,
          "A man's wife and daughter disappear in a hospital and the staff claims they were never admitted.", "2019" },
      { "Night Moves", Category.THRILLER, "Three radical environmentalists plan to blow up a dam in rural Oregon.",
          "2013" },
      { "The Invitation", Category.THRILLER,
          "A man growing increasingly suspicious of his ex-wife's new husband during a dinner party.", "2015" },
      { "I Saw the Devil", Category.THRILLER,
          "A secret agent blurs the line between good and evil in a relentless, brutal pursuit of a serial killer.",
          "2010" },
      { "Mother!", Category.THRILLER,
          "A couple's relationship is tested when uninvited guests arrive at their home, disturbing their tranquil existence.",
          "2017" },
      { "Haunt", Category.THRILLER,
          "A group of friends enter a haunted house attraction on Halloween night, only to discover it is run by real killers.",
          "2019" },
      { "Clue", Category.THRILLER,
          "Based on the board game, six guests at a dinner party are potential suspects when the host is found murdered.",
          "1985" },
      { "Knives Out", Category.THRILLER,
          "A detective investigates the death of a wealthy crime novelist during a family gathering.", "2019" },
      { "Ready or Not", Category.THRILLER,
          "A bride's wedding night takes a dark turn when she discovers her new in-laws plan to hunt her down.",
          "2019" },
      { "Run Rabbit Run", Category.THRILLER,
          "A woman is unsettled by her daughter's increasingly strange behavior after her estranged father dies.",
          "2023" },

      // ROMANCE
      { "Titanic", Category.ROMANCE,
          "A seventeen-year-old aristocrat and a kind but poor artist fall in love aboard the ill-fated voyage.",
          "1997" },
      { "The Notebook", Category.ROMANCE,
          "A couple who fell in love as teenagers reconnect decades later despite the differences in their backgrounds.",
          "2004" },
      { "Pride and Prejudice", Category.ROMANCE,
          "Lively Elizabeth Bennet meets proud Mr. Darcy and prejudice must be overcome before love can follow.",
          "2005" },
      { "La La Land", Category.ROMANCE,
          "A jazz musician and an aspiring actress fall in love in Los Angeles while chasing their dreams.", "2016" },
      { "Eternal Sunshine of the Spotless Mind", Category.ROMANCE,
          "After a painful breakup, a couple undergoes a procedure to erase each other from their memories.", "2004" },
      { "Casablanca", Category.ROMANCE,
          "An American expatriate in Morocco must choose between love and virtue when his former lover arrives.",
          "1942" },
      { "Roman Holiday", Category.ROMANCE,
          "A bored and sheltered princess slips away for a secret day in Rome, where she meets a reporter.", "1953" },
      { "Before Sunrise", Category.ROMANCE,
          "A young American man and a French woman meet on a train and spend a night together in Vienna.", "1995" },
      { "Before Sunset", Category.ROMANCE,
          "Nine years after their first meeting, the couple reunites in Paris for a brief afternoon.", "2004" },
      { "Before Midnight", Category.ROMANCE,
          "The couple is now in a committed relationship, and they confront the difficulties of long-term love in Greece.",
          "2013" },
      { "In the Mood for Love", Category.ROMANCE,
          "Two neighbors in 1960s Hong Kong develop an intense emotional bond after discovering their spouses are having an affair.",
          "2000" },
      { "Portrait of a Lady on Fire", Category.ROMANCE,
          "A painter falls in love with the woman she is commissioned to secretly paint on an isolated island.",
          "2019" },
      { "Normal People", Category.ROMANCE,
          "Two students in Ireland navigate an intense relationship through college and beyond.", "2020" },
      { "Call Me by Your Name", Category.ROMANCE,
          "A seventeen-year-old and an older American student develop a romance in 1980s Italy.", "2017" },
      { "Brokeback Mountain", Category.ROMANCE,
          "Two cowboys fall in love while herding sheep, and struggle with their feelings over two decades.", "2005" },
      { "Carol", Category.ROMANCE,
          "A young photographer falls for an older woman in 1950s New York, who is in the middle of a difficult divorce.",
          "2015" },
      { "The Shape of Water", Category.ROMANCE,
          "A mute janitor at a government laboratory falls in love with an amphibious creature being held captive.",
          "2017" },
      { "Her", Category.ROMANCE, "A lonely writer develops an unlikely relationship with an AI operating system.",
          "2013" },
      { "500 Days of Summer", Category.ROMANCE,
          "A man reflects on his failed relationship with a woman who didn't believe in love.", "2009" },
      { "Blue Valentine", Category.ROMANCE,
          "A couple examines the beginning and end of their relationship simultaneously.", "2010" },
      { "A Star Is Born", Category.ROMANCE,
          "A seasoned musician helps a young singer find fame, even as alcohol abuse sends his own career spiraling.",
          "2018" },
      { "Atonement", Category.ROMANCE, "A misunderstood incident tears apart two young lovers during World War II.",
          "2007" },
      { "Love, Rosie", Category.ROMANCE,
          "Two childhood best friends navigate missed chances and poor timing in their relationship.", "2014" },
      { "The Fault in Our Stars", Category.ROMANCE,
          "Two teenagers with cancer fall in love and take a trip to Amsterdam to meet their favorite author.",
          "2014" },
      { "To All the Boys I've Loved Before", Category.ROMANCE,
          "A high school girl's secret love letters are mailed out to all the boys she has ever loved.", "2018" },
      { "Letters to Juliet", Category.ROMANCE,
          "An American woman finds an unanswered love letter in Verona and sets out to find its writer.", "2010" },
      { "About Time", Category.ROMANCE,
          "A man who can time travel uses his ability to find love, and then learns some things can't be changed.",
          "2013" },
      { "Crazy Rich Asians", Category.ROMANCE,
          "A New York economics professor travels to Singapore with her boyfriend to meet his extremely wealthy family.",
          "2018" },
      { "Mamma Mia!", Category.ROMANCE,
          "A young woman about to be married invites three of her mother's ex-lovers to her wedding.", "2008" },
      { "The Proposal", Category.ROMANCE,
          "A pushy boss forces her assistant to pose as her fiancé so she can stay in the U.S., visiting his family in Alaska.",
          "2009" },
      { "My Best Friend's Wedding", Category.ROMANCE,
          "A food critic tries to break up her best friend's engagement when she realizes she is in love with him.",
          "1997" },
      { "When Harry Met Sally", Category.ROMANCE,
          "Two people become close friends over many years, despite a question of whether men and women can really be just friends.",
          "1989" },
      { "You've Got Mail", Category.ROMANCE,
          "Two business rivals are unknowingly falling in love online while feuding over their bookstores.", "1998" },
      { "Sleepless in Seattle", Category.ROMANCE,
          "A recently widowed man's son calls a radio talk-show and his story captivates a woman engaged to another man.",
          "1993" },
      { "Notting Hill", Category.ROMANCE,
          "A British bookshop owner crosses paths with the world's most famous film actress.", "1999" },
      { "Love Actually", Category.ROMANCE,
          "Follows the lives of eight very different couples dealing with their love lives in the weeks before Christmas.",
          "2003" },
      { "The Holiday", Category.ROMANCE,
          "Two women, both in dire need of a vacation, swap homes and fall in love with local men.", "2006" },
      { "Hitch", Category.ROMANCE,
          "A professional 'date doctor' falls for a gossip columnist who is writing an expose on him.", "2005" },
      { "10 Things I Hate About You", Category.ROMANCE,
          "A new student and his friend try to date two sisters whose father refuses to let them.", "1999" },
      { "Say Anything", Category.ROMANCE,
          "A noble underachiever and a beautiful valedictorian fall in love the summer before she leaves for England.",
          "1989" },
      { "Pretty Woman", Category.ROMANCE,
          "A business magnate hires a prostitute to be his companion for several business events, and they develop feelings.",
          "1990" },
      { "My Big Fat Greek Wedding", Category.ROMANCE,
          "A Greek woman falls in love with a non-Greek man, and has the challenge of bringing him home to meet her family.",
          "2002" },
      { "Bridget Jones's Diary", Category.ROMANCE,
          "A British woman resolves to improve her life after a disastrous New Year, and navigates two very different suitors.",
          "2001" },
      { "The Princess Bride", Category.ROMANCE,
          "A farmhand rescues his true love from a forced marriage while also battling a prince and his henchmen.",
          "1987" },
      { "Emma", Category.ROMANCE,
          "A young woman is convinced she has the ability to matchmake but fails to see love blooming under her nose.",
          "2020" },
      { "Little Women", Category.ROMANCE,
          "Jo March reflects on her life and her sisters' lives as they come of age in America after the Civil War.",
          "2019" },
      { "An Affair to Remember", Category.ROMANCE,
          "A couple meets and falls in love on a transatlantic voyage, but must return to their current lives first.",
          "1957" },
      { "Always Be My Maybe", Category.ROMANCE,
          "Two estranged childhood best friends reconnect as adults and realize their feelings for each other.",
          "2019" },
      { "The Sun Also Rises", Category.ROMANCE,
          "American and British expatriates travel from Paris to Spain to watch the running of the bulls and bullfighting.",
          "1957" },
      { "First Cow", Category.ROMANCE,
          "A cook befriends a Chinese immigrant in the Oregon Territory and the two devise a small but risky business scheme.",
          "2019" },

      // ANIMATION
      { "Toy Story", Category.ANIMATION,
          "A cowboy doll is threatened by a new space toy who has captured the imagination of their child owner.",
          "1995" },
      { "The Lion King", Category.ANIMATION,
          "A lion cub crown prince is exiled by his scheming uncle and must reclaim his homeland.", "1994" },
      { "Spirited Away", Category.ANIMATION,
          "A young girl enters a spirit world after her parents are transformed into pigs at an abandoned amusement park.",
          "2001" },
      { "Up", Category.ANIMATION,
          "An elderly widower sets out to fulfill his lifelong dream by tying thousands of balloons to his house, with an unexpected stowaway.",
          "2009" },
      { "Finding Nemo", Category.ANIMATION,
          "After his son is captured in the Great Barrier Reef, an overprotective clownfish embarks on a journey to bring him home.",
          "2003" },
      { "WALL-E", Category.ANIMATION,
          "A robot left to clean up a devastated Earth falls in love with a probe robot and follows her into space.",
          "2008" },
      { "Inside Out", Category.ANIMATION,
          "After moving to a new city, the emotions inside an 11-year-old girl's mind work to navigate new emotional landscapes.",
          "2015" },
      { "Coco", Category.ANIMATION,
          "A boy with a passion for music travels to the Land of the Dead to find his great-great-grandfather.",
          "2017" },
      { "Moana", Category.ANIMATION,
          "A determined teenager sets sail on a daring mission to save her people, encountering the demigod Maui along the way.",
          "2016" },
      { "Frozen", Category.ANIMATION,
          "A fearless optimist sets off on an epic journey to find her sister whose icy powers have trapped the kingdom in winter.",
          "2013" },
      { "Princess Mononoke", Category.ANIMATION,
          "A prince becomes involved in a struggle between forest gods and the humans that consume its resources.",
          "1997" },
      { "My Neighbor Totoro", Category.ANIMATION,
          "Two sisters move to the countryside and discover friendly forest spirits, including the large Totoro.",
          "1988" },
      { "Howl's Moving Castle", Category.ANIMATION,
          "A young milliner is cursed by a witch and befriends a wizard whose moving castle may hold the cure.",
          "2004" },
      { "Castle in the Sky", Category.ANIMATION,
          "A young boy and girl must keep a magic crystal from falling into the hands of government agents while searching for a legendary floating castle.",
          "1986" },
      { "Nausicaä of the Valley of the Wind", Category.ANIMATION,
          "A princess of a small kingdom uses her unique abilities to foster peace between warring factions in a post-apocalyptic world.",
          "1984" },
      { "Grave of the Fireflies", Category.ANIMATION,
          "A teenage boy and his young sister struggle to survive in Japan during World War II.", "1988" },
      { "Akira", Category.ANIMATION,
          "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic.",
          "1988" },
      { "Ghost in the Shell", Category.ANIMATION, "A cyborg cop and her partner hunt a mysterious and powerful hacker.",
          "1995" },
      { "Perfect Blue", Category.ANIMATION,
          "A pop singer gives up her career to become an actress, but she is stalked by a crazed fan and spirals into paranoia.",
          "1997" },
      { "Paprika", Category.ANIMATION,
          "A psychotherapist uses a device allowing therapists to enter their patients' dreams but it is stolen, causing chaos.",
          "2006" },
      { "The Tale of Princess Kaguya", Category.ANIMATION,
          "A tiny girl is found inside a bamboo stalk by a woodcutter and raised as a princess, but longs for the simple life.",
          "2013" },
      { "Wolf Children", Category.ANIMATION,
          "A young woman falls in love with a wolf man and raises their two half-wolf children after his death.",
          "2012" },
      { "Summer Wars", Category.ANIMATION,
          "A young math genius is dragged into a family gathering and must face a rogue artificial intelligence.",
          "2009" },
      { "Your Name", Category.ANIMATION,
          "A boy in Tokyo and a girl in rural Japan inexplicably begin to swap bodies, leading to a strange connection.",
          "2016" },
      { "A Silent Voice", Category.ANIMATION,
          "A young man attempts to make amends with a deaf girl he bullied in grade school.", "2016" },
      { "I Want to Eat Your Pancreas", Category.ANIMATION,
          "A high school boy secretly learns his classmate is living with a pancreatic disease and they become close.",
          "2018" },
      { "Weathering with You", Category.ANIMATION,
          "A runaway boy meets a girl who can manipulate the weather in rainy Tokyo.", "2019" },
      { "Belle", Category.ANIMATION,
          "A shy high-school student enters a virtual reality world where she becomes a celebrated singer.", "2021" },
      { "Mirai", Category.ANIMATION,
          "A four-year-old boy meets his future sister and other relatives from across time.", "2018" },
      { "Mary and the Witch's Flower", Category.ANIMATION,
          "A young girl discovers a flower that gives magical abilities for only one night.", "2017" },
      { "Bambi", Category.ANIMATION,
          "A young deer grows up in the forest with friends, but faces tragedy when hunters arrive.", "1942" },
      { "Snow White and the Seven Dwarfs", Category.ANIMATION,
          "A princess is poisoned by her jealous stepmother and protected by seven dwarfs until a prince arrives.",
          "1937" },
      { "Sleeping Beauty", Category.ANIMATION,
          "A princess is cursed to fall into a deep sleep by an evil fairy, and can only be awakened by true love's kiss.",
          "1959" },
      { "The Little Mermaid", Category.ANIMATION,
          "A mermaid princess dreams of becoming human and falls in love with a prince from the surface world.",
          "1989" },
      { "Aladdin", Category.ANIMATION,
          "A street urchin discovers a magic lamp and is granted three wishes by a Genie, and falls in love with a princess.",
          "1992" },
      { "Beauty and the Beast", Category.ANIMATION,
          "A young woman is held captive in a magical castle by a beastly prince and eventually falls in love with him.",
          "1991" },
      { "The Hunchback of Notre Dame", Category.ANIMATION,
          "Quasimodo the bell-ringer of Notre Dame falls in love with a beautiful Gypsy woman and protects her from a corrupt minister.",
          "1996" },
      { "Mulan", Category.ANIMATION,
          "A young Chinese woman secretly joins the army in place of her aging father to save him from death.",
          "1998" },
      { "Lilo and Stitch", Category.ANIMATION, "A young Hawaiian girl and an alien experiment form an unlikely family.",
          "2002" },
      { "Ratatouille", Category.ANIMATION,
          "A rat who can cook makes an unlikely alliance with a young kitchen worker at a famous Paris restaurant.",
          "2007" },
      { "The Incredibles", Category.ANIMATION,
          "A family of superheroes must balance suburban life with saving the world from a vengeful villain.", "2004" },
      { "Brave", Category.ANIMATION,
          "A Scottish princess defies tradition and must undo a beastly curse before it becomes permanent.", "2012" },
      { "Encanto", Category.ANIMATION,
          "A Colombian girl discovers that her magical family has begun to lose their powers.", "2021" },
      { "Soul", Category.ANIMATION,
          "A middle school band teacher falls into a coma and ends up in a realm between life and death.", "2020" },
      { "Turning Red", Category.ANIMATION,
          "A thirteen-year-old girl discovers she transforms into a giant red panda when she gets too excited.",
          "2022" },
      { "The Bad Guys", Category.ANIMATION,
          "A gang of infamous criminal animals attempt to become good as part of a deal with a governor.", "2022" },
      { "Puss in Boots: The Last Wish", Category.ANIMATION,
          "Puss in Boots discovers that his passion for adventure has taken a toll and he must find the Wishing Star.",
          "2022" },
      { "Spider-Man: Across the Spider-Verse", Category.ANIMATION,
          "Miles Morales travels the multiverse and meets a new team of Spider-People.", "2023" },
      { "Elemental", Category.ANIMATION,
          "A young woman made of fire meets a young man made of water in a city where elements coexist.", "2023" },
      { "Wish", Category.ANIMATION,
          "A young girl makes a wish to the stars and a tiny ball of boundless energy called Star answers.", "2023" },
      { "Migration", Category.ANIMATION,
          "An overprotective father duck reluctantly agrees to take his family on a migration journey.", "2023" },

      // DOCUMENTARY
      { "Planet Earth", Category.DOCUMENTARY,
          "David Attenborough narrates an unprecedented view of life on Earth in its most remote locations.", "2006" },
      { "Free Solo", Category.DOCUMENTARY,
          "Alex Honnold attempts to climb El Capitan without ropes in the most dangerous free solo in history.",
          "2018" },
      { "13th", Category.DOCUMENTARY,
          "Explores the intersection of race, justice, and mass incarceration in the United States.", "2016" },
      { "Jiro Dreams of Sushi", Category.DOCUMENTARY,
          "An 85-year-old sushi master runs a tiny restaurant in a Tokyo subway station with three Michelin stars.",
          "2011" },
      { "The Act of Killing", Category.DOCUMENTARY,
          "Former Indonesian death squad leaders are invited to reenact their mass killings in film genres of their choosing.",
          "2012" },
      { "Won't You Be My Neighbor?", Category.DOCUMENTARY,
          "An exploration of the life and legacy of Fred Rogers and his children's program.", "2018" },
      { "Icarus", Category.DOCUMENTARY,
          "A filmmaker who set out to document doping in sports uncovers a vast state-sponsored doping conspiracy in Russia.",
          "2017" },
      { "Tiger King", Category.DOCUMENTARY,
          "The story of eccentric big cat collectors who turn on each other when they discover they all share similar crimes.",
          "2020" },
      { "Seaspiracy", Category.DOCUMENTARY,
          "A filmmaker sets out to document the beauty of the ocean only to uncover deeply disturbing truths.",
          "2021" },
      { "The Social Dilemma", Category.DOCUMENTARY,
          "Tech experts explore the dangerous human impact of social networking.", "2020" },
      { "The Last Dance", Category.DOCUMENTARY,
          "The story of Michael Jordan, the Chicago Bulls dynasty, and the 1997-98 championship season.", "2020" },
      { "Making a Murderer", Category.DOCUMENTARY,
          "A questionable murder conviction of a Wisconsin man unravels into an investigation of the justice system.",
          "2015" },
      { "Wild Wild Country", Category.DOCUMENTARY,
          "A cult leader builds a utopian city in the Oregon desert and a massive scandal unfolds.", "2018" },
      { "Grizzly Man", Category.DOCUMENTARY,
          "A portrait of naturalist Timothy Treadwell, who spent 13 summers living among grizzly bears in Alaska.",
          "2005" },
      { "Exit Through the Gift Shop", Category.DOCUMENTARY,
          "Banksy turns the camera on the man who tried to film him, creating a documentary about street art.",
          "2010" },
      { "Capturing the Friedmans", Category.DOCUMENTARY,
          "A family's home movies reveal the truth behind a child abuse case that tore the family apart.", "2003" },
      { "My Octopus Teacher", Category.DOCUMENTARY,
          "A filmmaker forges an unusual friendship with a wild octopus living in a South African kelp forest.",
          "2020" },
      { "The Cove", Category.DOCUMENTARY,
          "Activists and filmmakers infiltrate a cove in Japan to investigate a secret dolphin slaughter.", "2009" },
      { "Roger & Me", Category.DOCUMENTARY,
          "Michael Moore attempts to interview the GM chairman after massive plant closures devastate Flint, Michigan.",
          "1989" },
      { "Super Size Me", Category.DOCUMENTARY,
          "A man exclusively eats McDonald's food for a month and documents the effects on his health.", "2004" },
      { "Food, Inc.", Category.DOCUMENTARY, "An unflattering look inside the American corporate food industry.",
          "2008" },
      { "Blackfish", Category.DOCUMENTARY,
          "Examines the circumstances surrounding the death of a trainer at SeaWorld and the captivity of killer whales.",
          "2013" },
      { "Virunga", Category.DOCUMENTARY,
          "Rangers risk their lives to protect endangered gorillas in the Congo jungle from militias and oil companies.",
          "2014" },
      { "Citizenfour", Category.DOCUMENTARY,
          "A filmmaker and journalist travel to Hong Kong to meet NSA whistleblower Edward Snowden.", "2014" },
      { "The Look of Silence", Category.DOCUMENTARY,
          "An Indonesian optometrist confronts the men who killed his brother during the 1965 purge.", "2014" },
      { "Waltz with Bashir", Category.DOCUMENTARY,
          "A former soldier investigates his lost memories of the 1982 Lebanon War.", "2008" },
      { "Stories We Tell", Category.DOCUMENTARY,
          "A filmmaker investigates the buried secrets of her family in personal testimonials and archival footage.",
          "2012" },
      { "How to Survive a Plague", Category.DOCUMENTARY,
          "The story of two coalitions that fought for AIDS research funding in New York City during the epidemic.",
          "2012" },
      { "The Square", Category.DOCUMENTARY,
          "Young Egyptian activists fight to keep alive the ideals of their revolution in Tahrir Square.", "2013" },
      { "The War Room", Category.DOCUMENTARY, "Goes behind the scenes of Bill Clinton's 1992 presidential campaign.",
          "1993" },
      { "Stories from the Stage", Category.DOCUMENTARY,
          "Ordinary people share extraordinary stories from their lives on stage.", "2018" },
      { "Night and Fog", Category.DOCUMENTARY, "A landmark documentary about the Nazi concentration camp system.",
          "1956" },
      { "Shoah", Category.DOCUMENTARY,
          "A nine-hour documentary about the Holocaust using survivor and perpetrator accounts.", "1985" },
      { "Hoop Dreams", Category.DOCUMENTARY,
          "Two inner-city Chicago boys are followed for five years as they pursue their dreams of basketball stardom.",
          "1994" },
      { "Crumb", Category.DOCUMENTARY,
          "An intimate portrait of underground cartoonist Robert Crumb, his family, and his world.", "1994" },
      { "American Movie", Category.DOCUMENTARY,
          "A filmmaker in Wisconsin struggles to finish his low-budget horror film.", "1999" },
      { "Anvil! The Story of Anvil", Category.DOCUMENTARY,
          "Two heavy-metal musicians who nearly made it big in the 1980s are still chasing their dream.", "2008" },
      { "Searching for Sugar Man", Category.DOCUMENTARY,
          "Two Cape Town fans investigate what happened to the 1970s American musician Rodriguez.", "2012" },
      { "Sour Grapes", Category.DOCUMENTARY,
          "A wine consultant is exposed as a fraudster who sold fake rare vintages to collectors.", "2016" },
      { "The Imposter", Category.DOCUMENTARY,
          "A Frenchman impersonates a missing 13-year-old Texas boy and is taken in by his grieving family.", "2012" },
      { "The Bridge", Category.DOCUMENTARY,
          "Documents the Golden Gate Bridge as a site of suicides and the impact on victims' families.", "2006" },
      { "Bowling for Columbine", Category.DOCUMENTARY,
          "Michael Moore investigates America's gun culture following the Columbine High School massacre.", "2002" },
      { "Manufacturing Consent", Category.DOCUMENTARY,
          "Noam Chomsky and Edward Herman argue that mass media serves the interests of powerful elites.", "1992" },
      { "I Am Chris Farley", Category.DOCUMENTARY,
          "A tribute to comedian Chris Farley through the testimonials of friends, family, and collaborators.",
          "2015" },
      { "Shut Up & Sing", Category.DOCUMENTARY,
          "The Dixie Chicks face fallout after a remark against President Bush days before the Iraq War begins.",
          "2006" },
      { "Some Kind of Monster", Category.DOCUMENTARY,
          "Metallica undergoes group therapy while recording their album St. Anger.", "2004" },
      { "Montage of Heck", Category.DOCUMENTARY,
          "An authorized documentary about Kurt Cobain's life and personal struggles.", "2015" },
      { "Amy", Category.DOCUMENTARY,
          "The life and career of singer Amy Winehouse, exploring her talent and personal demons.", "2015" },
      { "Senna", Category.DOCUMENTARY, "The life and death of legendary Formula One driver Ayrton Senna.", "2010" },
      { "Icarus", Category.DOCUMENTARY,
          "A cyclist discovers a state-sponsored Russian doping program after attempting to dope himself.", "2017" },
      { "Operation Odessa", Category.DOCUMENTARY,
          "The story of a Russian mobster, a Colombian cartel, and an American conman who tried to sell a Soviet submarine to the Medellin Cartel.",
          "2018" },

      // FANTASY
      { "The Lord of the Rings: The Fellowship of the Ring", Category.FANTASY,
          "A hobbit and his companions embark on a journey to destroy a powerful ring and save Middle-earth.", "2001" },
      { "Harry Potter and the Sorcerer's Stone", Category.FANTASY,
          "An orphan boy discovers he is a wizard and attends a school of magic.", "2001" },
      { "The Hobbit: An Unexpected Journey", Category.FANTASY,
          "A reluctant hobbit is swept into an epic quest to reclaim a dwarf king's mountain home from a dragon.",
          "2012" },
      { "Pan's Labyrinth", Category.FANTASY,
          "In post-Civil War Spain, a girl escapes into a fantasy world involving fauns and fairies.", "2006" },
      { "Princess Mononoke", Category.FANTASY,
          "A prince becomes involved in a struggle between forest gods and the humans consuming its resources.",
          "1997" },
      { "The Wizard of Oz", Category.FANTASY,
          "A Kansas farm girl is swept into the magical Land of Oz and seeks help from a wizard to return home.",
          "1939" },
      { "Alice in Wonderland", Category.FANTASY,
          "A young woman follows a white rabbit into a fantastical world beneath her feet.", "2010" },
      { "Stardust", Category.FANTASY,
          "A young man makes a deal with a witch and a prince to retrieve a fallen star from a magical kingdom.",
          "2007" },
      { "The Princess Bride", Category.FANTASY,
          "A farmhand rescues his true love from a forced marriage in a magical medieval land.", "1987" },
      { "Labyrinth", Category.FANTASY,
          "A teenage girl must solve a goblin king's labyrinth to rescue her baby brother.", "1986" },
      { "Legend", Category.FANTASY,
          "A forest boy must rescue his beloved from the Lord of Darkness who plans to use her to destroy the last unicorn.",
          "1985" },
      { "Willow", Category.FANTASY,
          "A small farmer is chosen to protect a magic baby from a wicked queen who wants it destroyed.", "1988" },
      { "The NeverEnding Story", Category.FANTASY,
          "A young boy reads a magical book that transports him into the land of Fantasia.", "1984" },
      { "Dragonheart", Category.FANTASY, "A knight and a dragon share a bond that ties their fates together.", "1996" },
      { "Eragon", Category.FANTASY, "A farm boy discovers a dragon egg and becomes a Dragon Rider.", "2006" },
      { "Inkheart", Category.FANTASY,
          "A man can bring fictional characters to life by reading aloud, unleashing a dangerous villain.", "2008" },
      { "The Spiderwick Chronicles", Category.FANTASY,
          "Twins discover their great-great-uncle's guide to faeries and are pulled into a dangerous magical world.",
          "2008" },
      { "Percy Jackson & the Olympians", Category.FANTASY,
          "A boy discovers he is the son of a Greek god and must prevent a war among the Olympians.", "2010" },
      { "Beautiful Creatures", Category.FANTASY,
          "A teenager falls for a girl who is a supernatural being with a destiny that could doom them both.", "2013" },
      { "Seventh Son", Category.FANTASY,
          "A young man becomes an apprentice to an old spook in order to battle malevolent witches and monsters.",
          "2014" },
      { "The Huntsman: Winter's War", Category.FANTASY,
          "Two warriors fight back against a sorcerer who has stolen the Enchanted Mirror.", "2016" },
      { "Warcraft", Category.FANTASY,
          "As an Orc horde invades a human kingdom, leaders from both sides must decide to fight or forge a peace.",
          "2016" },
      { "Fantastic Beasts and Where to Find Them", Category.FANTASY,
          "A magizoologist arrives in New York and releases magical creatures, uncovering a dark conspiracy.", "2016" },
      { "Doctor Strange", Category.FANTASY,
          "A brilliant surgeon is injured and discovers the world of magic and alternate dimensions.", "2016" },
      { "Thor", Category.FANTASY,
          "An arrogant prince from Asgard is cast down to Earth and must prove himself worthy to wield his hammer.",
          "2011" },
      { "Black Panther", Category.FANTASY,
          "The king of a hidden technological African nation must defend his throne and country.", "2018" },
      { "Avengers: Infinity War", Category.FANTASY,
          "Heroes from across the Marvel universe unite to stop Thanos from collecting the Infinity Stones.", "2018" },
      { "Aquaman", Category.FANTASY,
          "The heir to the underwater kingdom of Atlantis must unite its people against a threat from the surface world.",
          "2018" },
      { "Shazam!", Category.FANTASY, "A teenage boy can transform into an adult superhero by saying one magic word.",
          "2019" },
      { "The Lion, the Witch and the Wardrobe", Category.FANTASY,
          "Four siblings discover a magical world in a wardrobe and help a lion free it from a white witch.", "2005" },
      { "Eragon", Category.FANTASY,
          "A young farmer becomes a Dragon Rider and must protect the realm from an evil king.", "2006" },
      { "Onward", Category.FANTASY,
          "Two elf brothers embark on a quest to discover if magic still exists so they can spend one more day with their late father.",
          "2020" },
      { "Soul", Category.FANTASY, "A musician on the verge of his big break slips into a realm between life and death.",
          "2020" },
      { "Raya and the Last Dragon", Category.FANTASY,
          "In a world threatened by an evil force, a lone warrior seeks the last dragon to restore harmony.", "2021" },
      { "Lightyear", Category.FANTASY,
          "The origin story of Buzz Lightyear, a human space ranger who inspired a toy line.", "2022" },
      { "Strange World", Category.FANTASY,
          "The Clade family discovers an uncharted and dangerous land filled with mysterious creatures.", "2022" },
      { "Wish", Category.FANTASY,
          "A young girl's wish is answered by a magical star that begins to unravel something sinister.", "2023" },
      { "The Marvels", Category.FANTASY,
          "Carol Danvers, Monica Rambeau, and Kamala Khan have their powers entangled and must work together.",
          "2023" },
      { "Aquaman and the Lost Kingdom", Category.FANTASY,
          "Arthur Curry must forge an alliance with his jailed brother to protect Atlantis from an ancient power.",
          "2023" },
      { "Haunted Mansion", Category.FANTASY,
          "A woman and her son turn to a motley crew of so-called ghost experts for help after their new home proves to be haunted.",
          "2023" },
      { "The Flash", Category.FANTASY,
          "Barry Allen uses his super speed to travel back in time and prevent his mother's murder.", "2023" },
      { "Dungeons & Dragons: Honor Among Thieves", Category.FANTASY,
          "A charming thief and a band of misfits embark on an epic heist to retrieve a lost relic.", "2023" },
      { "Nimona", Category.FANTASY,
          "A knight in a futuristic medieval world teams up with a shapeshifter to clear his name.", "2023" },
      { "Elemental", Category.FANTASY,
          "Fire, water, land, and air elements coexist in a single city in an elemental world.", "2023" },
      { "Renfield", Category.FANTASY,
          "Renfield escapes from Dracula's grasp and tries to live as a normal person in New York City.", "2023" },
      { "65", Category.FANTASY,
          "An astronaut crash-lands on an unknown planet, only to discover he's landed on Earth, 65 million years ago.",
          "2023" },
      { "Dungeons & Dragons: The Book of Vile Darkness", Category.FANTASY,
          "A paladin goes undercover in an evil adventuring party to find his kidnapped father.", "2012" },
      { "The Sorcerer's Apprentice", Category.FANTASY,
          "A physics student is recruited by a wizard to help him fight against dark forces.", "2010" },
      { "The Golden Compass", Category.FANTASY,
          "A young girl living in a parallel universe travels north with a talking polar bear to rescue kidnapped children.",
          "2007" },
  };

  public static Movie[] generate(int count) {
    Movie[] movies = new Movie[count];
    int dataSize = MOVIE_DATA.length;
    for (int i = 0; i < count; i++) {
      Object[] data = MOVIE_DATA[i % dataSize];
      String title = (String) data[0];
      Category category = (Category) data[1];
      String description = (String) data[2];
      String year = (String) data[3];

      if (i >= dataSize) {
        int cycle = (i / dataSize) + 1;
        title = title + " (Remastered " + (2000 + cycle) + ")";
      }

      movies[i] = new Movie(i + 1, title, category, description, year);
    }

    return movies;
  }
}
